title: Bora's Website
author: GitHub User
email: btarhan@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  I love computer science !

# social links
github_username:  BoraArhan # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-hacker
